name = "node_socket_client"
version = "1.0.0"
target = "javascript"

description = "Bindings to Node's TCP socket client"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "node-socket-client" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
